# Generated by Django 5.1.6 on 2025-03-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeathers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weathers.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
