# Generated by Django 5.1.6 on 2025-03-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0002_cityweathers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(choices=[('LT', 'Lietuva'), ('LV', 'Latvija'), ('EST', 'Estija')], default='Lietuva', max_length=100),
        ),
    ]
